# Generated by Django 5.0.7 on 2024-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cyper_app", "0002_user_delete_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
